NODE_DISPLAY_NAME_MAPPINGS = {
    **ULTRA_REP_NODE_DISPLAY_NAME_MAPPINGS,
    **REP_NODE_DISPLAY_NAME_MAPPINGS
}

NODE_CLASS_MAPPINGS = {
    **ULTRA_REP_NODE_CLASS_MAPPINGS,
    **REP_NODE_CLASS_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
